// <auto-generated />
using Escalonamento.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Escalonamento.Migrations
{
    [DbContext(typeof(EscalonamentoContext))]
    partial class EscalonamentoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Escalonamento.Models.Trocas", b =>
                {
                    b.Property<int>("TrocasId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dia1");

                    b.Property<int>("Dia2");

                    b.Property<string>("Nome1")
                        .IsRequired();

                    b.Property<string>("Nome2")
                        .IsRequired();

                    b.Property<string>("Turno1")
                        .IsRequired();

                    b.Property<string>("Turno2")
                        .IsRequired();

                    b.HasKey("TrocasId");

                    b.ToTable("Trocas");
                });

            modelBuilder.Entity("Escalonamento.Models.Veiculos", b =>
                {
                    b.Property<int>("VeiculosId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Disponibilidade");

                    b.Property<string>("Marca")
                        .IsRequired();

                    b.Property<string>("NumMatricula")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
